// MMSI Maritime Identification Digits → country + flag
// First 3 digits of any MMSI number are the MID code

const MID_MAP: Record<number, { country: string; flag: string }> = {
    201: { country: 'Albania', flag: '🇦🇱' },
    202: { country: 'Andorra', flag: '🇦🇩' },
    203: { country: 'Austria', flag: '🇦🇹' },
    205: { country: 'Belgium', flag: '🇧🇪' },
    207: { country: 'Belarus', flag: '🇧🇾' },
    208: { country: 'Bulgaria', flag: '🇧🇬' },
    212: { country: 'Cyprus', flag: '🇨🇾' },
    213: { country: 'Germany', flag: '🇩🇪' },
    214: { country: 'Germany', flag: '🇩🇪' },
    215: { country: 'Malta', flag: '🇲🇹' },
    219: { country: 'Denmark', flag: '🇩🇰' },
    220: { country: 'Denmark', flag: '🇩🇰' },
    224: { country: 'Spain', flag: '🇪🇸' },
    225: { country: 'Spain', flag: '🇪🇸' },
    226: { country: 'France', flag: '🇫🇷' },
    227: { country: 'France', flag: '🇫🇷' },
    228: { country: 'France', flag: '🇫🇷' },
    230: { country: 'Finland', flag: '🇫🇮' },
    231: { country: 'Faroe Islands', flag: '🇫🇴' },
    232: { country: 'United Kingdom', flag: '🇬🇧' },
    233: { country: 'United Kingdom', flag: '🇬🇧' },
    234: { country: 'United Kingdom', flag: '🇬🇧' },
    235: { country: 'United Kingdom', flag: '🇬🇧' },
    236: { country: 'Gibraltar', flag: '🇬🇮' },
    237: { country: 'Greece', flag: '🇬🇷' },
    238: { country: 'Croatia', flag: '🇭🇷' },
    239: { country: 'Greece', flag: '🇬🇷' },
    240: { country: 'Greece', flag: '🇬🇷' },
    241: { country: 'Greece', flag: '🇬🇷' },
    242: { country: 'Morocco', flag: '🇲🇦' },
    244: { country: 'Netherlands', flag: '🇳🇱' },
    245: { country: 'Netherlands', flag: '🇳🇱' },
    246: { country: 'Netherlands', flag: '🇳🇱' },
    247: { country: 'Italy', flag: '🇮🇹' },
    248: { country: 'Malta', flag: '🇲🇹' },
    249: { country: 'Malta', flag: '🇲🇹' },
    250: { country: 'Ireland', flag: '🇮🇪' },
    251: { country: 'Iceland', flag: '🇮🇸' },
    252: { country: 'Liechtenstein', flag: '🇱🇮' },
    253: { country: 'Luxembourg', flag: '🇱🇺' },
    254: { country: 'Monaco', flag: '🇲🇨' },
    255: { country: 'Portugal', flag: '🇵🇹' },
    256: { country: 'Malta', flag: '🇲🇹' },
    257: { country: 'Norway', flag: '🇳🇴' },
    258: { country: 'Norway', flag: '🇳🇴' },
    259: { country: 'Norway', flag: '🇳🇴' },
    261: { country: 'Poland', flag: '🇵🇱' },
    262: { country: 'Montenegro', flag: '🇲🇪' },
    263: { country: 'Portugal', flag: '🇵🇹' },
    264: { country: 'Romania', flag: '🇷🇴' },
    265: { country: 'Sweden', flag: '🇸🇪' },
    266: { country: 'Sweden', flag: '🇸🇪' },
    267: { country: 'Slovakia', flag: '🇸🇰' },
    268: { country: 'San Marino', flag: '🇸🇲' },
    269: { country: 'Switzerland', flag: '🇨🇭' },
    270: { country: 'Czech Republic', flag: '🇨🇿' },
    271: { country: 'Turkey', flag: '🇹🇷' },
    272: { country: 'Ukraine', flag: '🇺🇦' },
    273: { country: 'Russia', flag: '🇷🇺' },
    274: { country: 'North Macedonia', flag: '🇲🇰' },
    275: { country: 'Latvia', flag: '🇱🇻' },
    276: { country: 'Estonia', flag: '🇪🇪' },
    277: { country: 'Lithuania', flag: '🇱🇹' },
    278: { country: 'Slovenia', flag: '🇸🇮' },
    279: { country: 'Serbia', flag: '🇷🇸' },
    301: { country: 'Anguilla', flag: '🇦🇮' },
    303: { country: 'United States', flag: '🇺🇸' },
    304: { country: 'Antigua & Barbuda', flag: '🇦🇬' },
    305: { country: 'Antigua & Barbuda', flag: '🇦🇬' },
    306: { country: 'Netherlands Antilles', flag: '🇧🇶' },
    307: { country: 'Aruba', flag: '🇦🇼' },
    308: { country: 'Bahamas', flag: '🇧🇸' },
    309: { country: 'Bahamas', flag: '🇧🇸' },
    310: { country: 'Bermuda', flag: '🇧🇲' },
    311: { country: 'Bahamas', flag: '🇧🇸' },
    316: { country: 'Canada', flag: '🇨🇦' },
    319: { country: 'Cayman Islands', flag: '🇰🇾' },
    321: { country: 'Cuba', flag: '🇨🇺' },
    323: { country: 'Dominica', flag: '🇩🇲' },
    325: { country: 'Dominican Republic', flag: '🇩🇴' },
    327: { country: 'Haiti', flag: '🇭🇹' },
    329: { country: 'Guadeloupe', flag: '🇬🇵' },
    330: { country: 'Grenada', flag: '🇬🇩' },
    331: { country: 'Greenland', flag: '🇬🇱' },
    332: { country: 'Guatemala', flag: '🇬🇹' },
    334: { country: 'Honduras', flag: '🇭🇳' },
    336: { country: 'Jamaica', flag: '🇯🇲' },
    338: { country: 'United States', flag: '🇺🇸' },
    339: { country: 'Martinique', flag: '🇲🇶' },
    341: { country: 'Mexico', flag: '🇲🇽' },
    345: { country: 'Nicaragua', flag: '🇳🇮' },
    347: { country: 'Panama', flag: '🇵🇦' },
    348: { country: 'Panama', flag: '🇵🇦' },
    349: { country: 'Panama', flag: '🇵🇦' },
    351: { country: 'Panama', flag: '🇵🇦' },
    352: { country: 'Panama', flag: '🇵🇦' },
    353: { country: 'Panama', flag: '🇵🇦' },
    354: { country: 'Panama', flag: '🇵🇦' },
    355: { country: 'Panama', flag: '🇵🇦' },
    356: { country: 'Panama', flag: '🇵🇦' },
    357: { country: 'Panama', flag: '🇵🇦' },
    358: { country: 'Puerto Rico', flag: '🇵🇷' },
    359: { country: 'El Salvador', flag: '🇸🇻' },
    361: { country: 'Trinidad & Tobago', flag: '🇹🇹' },
    362: { country: 'Trinidad & Tobago', flag: '🇹🇹' },
    366: { country: 'United States', flag: '🇺🇸' },
    367: { country: 'United States', flag: '🇺🇸' },
    368: { country: 'United States', flag: '🇺🇸' },
    369: { country: 'United States', flag: '🇺🇸' },
    370: { country: 'Panama', flag: '🇵🇦' },
    371: { country: 'Panama', flag: '🇵🇦' },
    372: { country: 'Panama', flag: '🇵🇦' },
    373: { country: 'Panama', flag: '🇵🇦' },
    374: { country: 'Panama', flag: '🇵🇦' },
    375: { country: 'Saint Vincent', flag: '🇻🇨' },
    376: { country: 'Saint Vincent', flag: '🇻🇨' },
    377: { country: 'Saint Vincent', flag: '🇻🇨' },
    378: { country: 'British Virgin Islands', flag: '🇻🇬' },
    379: { country: 'US Virgin Islands', flag: '🇻🇮' },
    401: { country: 'Afghanistan', flag: '🇦🇫' },
    403: { country: 'Saudi Arabia', flag: '🇸🇦' },
    405: { country: 'Bangladesh', flag: '🇧🇩' },
    408: { country: 'Bahrain', flag: '🇧🇭' },
    410: { country: 'Bhutan', flag: '🇧🇹' },
    412: { country: 'China', flag: '🇨🇳' },
    413: { country: 'China', flag: '🇨🇳' },
    414: { country: 'China', flag: '🇨🇳' },
    416: { country: 'Taiwan', flag: '🇹🇼' },
    417: { country: 'Sri Lanka', flag: '🇱🇰' },
    419: { country: 'India', flag: '🇮🇳' },
    422: { country: 'Iran', flag: '🇮🇷' },
    423: { country: 'Azerbaijan', flag: '🇦🇿' },
    425: { country: 'Iraq', flag: '🇮🇶' },
    428: { country: 'Israel', flag: '🇮🇱' },
    431: { country: 'Japan', flag: '🇯🇵' },
    432: { country: 'Japan', flag: '🇯🇵' },
    434: { country: 'Turkmenistan', flag: '🇹🇲' },
    436: { country: 'Kazakhstan', flag: '🇰🇿' },
    437: { country: 'Uzbekistan', flag: '🇺🇿' },
    438: { country: 'Jordan', flag: '🇯🇴' },
    440: { country: 'South Korea', flag: '🇰🇷' },
    441: { country: 'South Korea', flag: '🇰🇷' },
    443: { country: 'Palestine', flag: '🇵🇸' },
    445: { country: 'North Korea', flag: '🇰🇵' },
    447: { country: 'Kuwait', flag: '🇰🇼' },
    450: { country: 'Lebanon', flag: '🇱🇧' },
    451: { country: 'Kyrgyzstan', flag: '🇰🇬' },
    453: { country: 'Macao', flag: '🇲🇴' },
    455: { country: 'Maldives', flag: '🇲🇻' },
    457: { country: 'Mongolia', flag: '🇲🇳' },
    459: { country: 'Nepal', flag: '🇳🇵' },
    461: { country: 'Oman', flag: '🇴🇲' },
    463: { country: 'Pakistan', flag: '🇵🇰' },
    466: { country: 'Qatar', flag: '🇶🇦' },
    468: { country: 'Syria', flag: '🇸🇾' },
    470: { country: 'UAE', flag: '🇦🇪' },
    471: { country: 'UAE', flag: '🇦🇪' },
    472: { country: 'Tajikistan', flag: '🇹🇯' },
    473: { country: 'Yemen', flag: '🇾🇪' },
    477: { country: 'Hong Kong', flag: '🇭🇰' },
    478: { country: 'Bosnia & Herzegovina', flag: '🇧🇦' },
    501: { country: 'Antarctica', flag: '🇦🇶' },
    503: { country: 'Australia', flag: '🇦🇺' },
    506: { country: 'Myanmar', flag: '🇲🇲' },
    508: { country: 'Brunei', flag: '🇧🇳' },
    510: { country: 'Micronesia', flag: '🇫🇲' },
    511: { country: 'Palau', flag: '🇵🇼' },
    512: { country: 'New Zealand', flag: '🇳🇿' },
    514: { country: 'Cambodia', flag: '🇰🇭' },
    515: { country: 'Cambodia', flag: '🇰🇭' },
    516: { country: 'Christmas Island', flag: '🇨🇽' },
    518: { country: 'Cook Islands', flag: '🇨🇰' },
    520: { country: 'Fiji', flag: '🇫🇯' },
    523: { country: 'Cocos Islands', flag: '🇨🇨' },
    525: { country: 'Indonesia', flag: '🇮🇩' },
    529: { country: 'Kiribati', flag: '🇰🇮' },
    531: { country: 'Laos', flag: '🇱🇦' },
    533: { country: 'Malaysia', flag: '🇲🇾' },
    536: { country: 'Marshall Islands', flag: '🇲🇭' },
    538: { country: 'Marshall Islands', flag: '🇲🇭' },
    540: { country: 'New Caledonia', flag: '🇳🇨' },
    542: { country: 'Niue', flag: '🇳🇺' },
    544: { country: 'Nauru', flag: '🇳🇷' },
    546: { country: 'French Polynesia', flag: '🇵🇫' },
    548: { country: 'Philippines', flag: '🇵🇭' },
    553: { country: 'Papua New Guinea', flag: '🇵🇬' },
    555: { country: 'Pitcairn Island', flag: '🇵🇳' },
    557: { country: 'Solomon Islands', flag: '🇸🇧' },
    559: { country: 'American Samoa', flag: '🇦🇸' },
    561: { country: 'Samoa', flag: '🇼🇸' },
    563: { country: 'Singapore', flag: '🇸🇬' },
    564: { country: 'Singapore', flag: '🇸🇬' },
    565: { country: 'Singapore', flag: '🇸🇬' },
    566: { country: 'Singapore', flag: '🇸🇬' },
    567: { country: 'Thailand', flag: '🇹🇭' },
    570: { country: 'Tonga', flag: '🇹🇴' },
    572: { country: 'Tuvalu', flag: '🇹🇻' },
    574: { country: 'Vietnam', flag: '🇻🇳' },
    576: { country: 'Vanuatu', flag: '🇻🇺' },
    577: { country: 'Vanuatu', flag: '🇻🇺' },
    578: { country: 'Wallis & Futuna', flag: '🇼🇫' },
    601: { country: 'South Africa', flag: '🇿🇦' },
    603: { country: 'Angola', flag: '🇦🇴' },
    605: { country: 'Algeria', flag: '🇩🇿' },
    607: { country: 'Saint Paul Island', flag: '🇫🇷' },
    608: { country: 'Ascension Island', flag: '🇸🇭' },
    609: { country: 'Burundi', flag: '🇧🇮' },
    610: { country: 'Benin', flag: '🇧🇯' },
    611: { country: 'Botswana', flag: '🇧🇼' },
    612: { country: 'Central African Republic', flag: '🇨🇫' },
    613: { country: 'Cameroon', flag: '🇨🇲' },
    615: { country: 'Congo', flag: '🇨🇬' },
    616: { country: 'Comoros', flag: '🇰🇲' },
    617: { country: 'Cape Verde', flag: '🇨🇻' },
    618: { country: 'Antarctica', flag: '🇦🇶' },
    619: { country: 'Ivory Coast', flag: '🇨🇮' },
    620: { country: 'Djibouti', flag: '🇩🇯' },
    621: { country: 'Egypt', flag: '🇪🇬' },
    622: { country: 'Ethiopia', flag: '🇪🇹' },
    624: { country: 'Eritrea', flag: '🇪🇷' },
    625: { country: 'Gabon', flag: '🇬🇦' },
    626: { country: 'Ghana', flag: '🇬🇭' },
    627: { country: 'Gambia', flag: '🇬🇲' },
    629: { country: 'Guinea-Bissau', flag: '🇬🇼' },
    630: { country: 'Equatorial Guinea', flag: '🇬🇶' },
    631: { country: 'Guinea', flag: '🇬🇳' },
    632: { country: 'Burkina Faso', flag: '🇧🇫' },
    633: { country: 'Kenya', flag: '🇰🇪' },
    634: { country: 'Liberia', flag: '🇱🇷' },
    635: { country: 'Liberia', flag: '🇱🇷' },
    636: { country: 'Liberia', flag: '🇱🇷' },
    637: { country: 'Liberia', flag: '🇱🇷' },
    638: { country: 'Libya', flag: '🇱🇾' },
    642: { country: 'Madagascar', flag: '🇲🇬' },
    644: { country: 'Mauritius', flag: '🇲🇺' },
    645: { country: 'Mali', flag: '🇲🇱' },
    647: { country: 'Mauritania', flag: '🇲🇷' },
    649: { country: 'Mozambique', flag: '🇲🇿' },
    650: { country: 'Malawi', flag: '🇲🇼' },
    654: { country: 'Niger', flag: '🇳🇪' },
    655: { country: 'Nigeria', flag: '🇳🇬' },
    656: { country: 'Nigeria', flag: '🇳🇬' },
    657: { country: 'Nigeria', flag: '🇳🇬' },
    659: { country: 'Namibia', flag: '🇳🇦' },
    660: { country: 'Reunion', flag: '🇷🇪' },
    661: { country: 'Rwanda', flag: '🇷🇼' },
    662: { country: 'Sudan', flag: '🇸🇩' },
    663: { country: 'Senegal', flag: '🇸🇳' },
    664: { country: 'Seychelles', flag: '🇸🇨' },
    665: { country: 'Saint Helena', flag: '🇸🇭' },
    666: { country: 'Somalia', flag: '🇸🇴' },
    667: { country: 'Sierra Leone', flag: '🇸🇱' },
    668: { country: 'Sao Tome & Principe', flag: '🇸🇹' },
    669: { country: 'Swaziland', flag: '🇸🇿' },
    670: { country: 'Chad', flag: '🇹🇩' },
    671: { country: 'Togo', flag: '🇹🇬' },
    672: { country: 'Tunisia', flag: '🇹🇳' },
    674: { country: 'Tanzania', flag: '🇹🇿' },
    675: { country: 'Uganda', flag: '🇺🇬' },
    676: { country: 'DR Congo', flag: '🇨🇩' },
    677: { country: 'Zimbabwe', flag: '🇿🇼' },
    678: { country: 'Zambia', flag: '🇿🇲' },
    679: { country: 'Morocco', flag: '🇲🇦' },
    701: { country: 'Argentina', flag: '🇦🇷' },
    710: { country: 'Brazil', flag: '🇧🇷' },
    720: { country: 'Bolivia', flag: '🇧🇴' },
    725: { country: 'Chile', flag: '🇨🇱' },
    730: { country: 'Colombia', flag: '🇨🇴' },
    735: { country: 'Ecuador', flag: '🇪🇨' },
    740: { country: 'Falkland Islands', flag: '🇫🇰' },
    745: { country: 'Guiana', flag: '🇬🇫' },
    750: { country: 'Guyana', flag: '🇬🇾' },
    755: { country: 'Paraguay', flag: '🇵🇾' },
    760: { country: 'Peru', flag: '🇵🇪' },
    765: { country: 'Suriname', flag: '🇸🇷' },
    770: { country: 'Uruguay', flag: '🇺🇾' },
    775: { country: 'Venezuela', flag: '🇻🇪' },
};

const UNKNOWN = { country: 'Unknown', flag: '🌐' };

export function lookupMmsiCountry(mmsi: number): { country: string; flag: string } {
    if (!mmsi || mmsi < 100000000) return UNKNOWN;
    const mid = Math.floor(mmsi / 1000000);
    return MID_MAP[mid] ?? UNKNOWN;
}
