// Aircraft Registration Prefixes -> Country mapping
// Source: ICAO Annex 7 / ITU-R Recommendation M.1141-1

const REG_PREFIXES: Record<string, string> = {
    'N': 'United States',
    'G-': 'United Kingdom',
    'F-': 'France',
    'D-': 'Germany',
    'I-': 'Italy',
    'JA': 'Japan',
    'HL': 'South Korea',
    'B-': 'China', // Also covers Taiwan (B-), but often B-XXXX is mainland
    'VH': 'Australia',
    'C-': 'Canada',
    'VT': 'India',
    'PP': 'Brazil',
    'PT': 'Brazil',
    'RA': 'Russia',
    'RF': 'Russia',
    'UR': 'Ukraine',
    'EC-': 'Spain',
    'PH-': 'Netherlands',
    'OO-': 'Belgium',
    'HB-': 'Switzerland',
    'OE-': 'Austria',
    'SE-': 'Sweden',
    'LN-': 'Norway',
    'OY-': 'Denmark',
    'OH-': 'Finland',
    'EI-': 'Ireland',
    'EJ-': 'Ireland',
    'CS-': 'Portugal',
    'SX-': 'Greece',
    'TC-': 'Turkey',
    'SP-': 'Poland',
    'OK-': 'Czech Republic',
    'HA-': 'Hungary',
    'LZ-': 'Bulgaria',
    'YR-': 'Romania',
    'YL-': 'Latvia',
    'ES-': 'Estonia',
    'LY-': 'Lithuania',
    '9H-': 'Malta',
    '5B-': 'Cyprus',
    'A6-': 'UAE',
    'A7-': 'Qatar',
    'A9C': 'Bahrain',
    'HZ-': 'Saudi Arabia',
    '4X-': 'Israel',
    'JY-': 'Jordan',
    'OD-': 'Lebanon',
    'YI-': 'Iraq',
    'EP-': 'Iran',
    'PK-': 'Indonesia',
    '9M-': 'Malaysia',
    'RP-': 'Philippines',
    'HS-': 'Thailand',
    '9V-': 'Singapore',
    'VN-': 'Vietnam',
    'XY-': 'Myanmar',
    'S2-': 'Bangladesh',
    '4R-': 'Sri Lanka',
    '9N-': 'Nepal',
    'XC-': 'Mexico',
    'XA-': 'Mexico',
    'XB-': 'Mexico',
    'CU-': 'Cuba',
    'HP-': 'Panama',
    'HK-': 'Colombia',
    'HC-': 'Ecuador',
    'OB-': 'Peru',
    'CC-': 'Chile',
    'LV-': 'Argentina',
    'LQ-': 'Argentina',
    'CX-': 'Uruguay',
    'YV-': 'Venezuela',
    'ZP-': 'Paraguay',
    'CP-': 'Bolivia',
    'FAC': 'Colombia',
    'ZS-': 'South Africa',
    'SU-': 'Egypt',
    '5N-': 'Nigeria',
    '5Y-': 'Kenya',
    '7T-': 'Algeria',
    'TS-': 'Tunisia',
    'CN-': 'Morocco',
    'ST-': 'Sudan',
    'ET-': 'Ethiopia',
    '5H-': 'Tanzania',
    'D2-': 'Angola',
    'V5-': 'Namibia',
    'A2-': 'Botswana',
    'C9-': 'Mozambique',
    'Z-': 'Zimbabwe',
    '9J-': 'Zambia',
    '9U-': 'Burundi',
    '5X-': 'Uganda',
    'T7-': 'San Marino',
    'C3-': 'Andorra',
    '4U-': 'United Nations',
    'ER-': 'Moldova',
    'EK-': 'Armenia',
    '4K-': 'Azerbaijan',
    'UP-': 'Kazakhstan',
    'UK-': 'Uzbekistan',
    'EY-': 'Tajikistan',
    'EX-': 'Kyrgyzstan',
    'EZ-': 'Turkmenistan',
    'MT-': 'Mongolia',
    '6V-': 'Senegal',
    '9G-': 'Ghana',
    'TU-': 'Ivory Coast',
    'TY-': 'Benin',
    '5U-': 'Niger',
    'V8-': 'Brunei',
    'V7-': 'Marshall Islands',
    'DQ-': 'Fiji',
    'P2-': 'Papua New Guinea',
    'ZK-': 'New Zealand',
    '3A-': 'Monaco',
    'LX-': 'Luxembourg',
    'OM-': 'Slovakia',
    'S5-': 'Slovenia',
    '9A-': 'Croatia',
    'E7-': 'Bosnia & Herzegovina',
    'ZA-': 'Albania',
    'Z3-': 'North Macedonia',
    '4O-': 'Montenegro',
    'YU-': 'Serbia',
    '5V-': 'Togo',
    '9L-': 'Sierra Leone',
    'EL-': 'Liberia',
    'J5-': 'Guinea-Bissau',
    '3X-': 'Guinea',
    'D4-': 'Cape Verde',
    'J2-': 'Djibouti',
    '5R-': 'Madagascar',
    '3B-': 'Mauritius',
    'S7-': 'Seychelles',
};

// Sort prefixes by length descending to ensure longest match is picked first (e.g., A9C vs A)
const SORTED_PREFIXES = Object.keys(REG_PREFIXES).sort((a, b) => b.length - a.length);

/**
 * Lookup country by aircraft registration / tail number.
 * Returns country name or null if no match found.
 */
export function lookupRegistrationCountry(reg: string | null): string | null {
    if (!reg) return null;
    const upper = reg.toUpperCase().trim();

    for (const prefix of SORTED_PREFIXES) {
        if (upper.startsWith(prefix)) {
            return REG_PREFIXES[prefix];
        }
    }

    return null;
}
